/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import com.bkap.dao.NguoiDungDAOImp;
import com.bkap.entities.NguoiDung;
import java.sql.Array;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author TaiyoNg
 */
public class UserIF extends javax.swing.JInternalFrame implements UserUpdate.CallbackUpdateUser{
    NguoiDungDAOImp nguoiDungDAOImp;
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    UserUpdate up = new UserUpdate(this);
    /**
     * Creates new form UserIF
     */

    @Override
    public void doUpdateUser(String id, String name, String email, String phone, String role) {
        try {
            updateNguoiDung(id, name, email, phone, role);
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin người dùng thành công", "Thông Báo", 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin người dùng không thành công", "Thông Báo", 1);
            e.printStackTrace();
        }
        displayNguoiDung();
    }

    
    public UserIF() {
        nguoiDungDAOImp = new NguoiDungDAOImp();
        initComponents();
        displayNguoiDung();
    }
    public void displayNguoiDung(){
        List<NguoiDung> data = nguoiDungDAOImp.toList();
        DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
        model.setRowCount(0);
        Calendar c = Calendar.getInstance();
        for (NguoiDung nd : data) {
            c.setTime(nd.getNgayTao());
            c.add(Calendar.DATE, 2);
            model.addRow(new Object[]{nd.getId(), nd.getTenNguoiDung(), nd.getEmail(), nd.getSdt(), nd.getRole(), sdf.format(c.getTime())});
        }
        tblUser.setModel(model);
    }
    public void updateNguoiDung(String id, String name, String email, String phone, String role){
        NguoiDung nd = new NguoiDung();
        nd.setId(id);
        nd.setTenNguoiDung(name);
        nd.setEmail(email);
        nd.setSdt(phone);
        nd.setRole(role);
        nguoiDungDAOImp.edit(nd);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUserSearch = new javax.swing.JTextField();
        btnUserSearch = new javax.swing.JButton();
        btnUserDelete = new javax.swing.JButton();
        btnUserUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        btnUserRefresh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboRole = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        pwdUserPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        pwdUserPasswordConfirm = new javax.swing.JPasswordField();
        btnAddUser = new javax.swing.JButton();
        btnRefreshAddUser = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Quản Lý Người Dùng");

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý người dùng");

        txtUserSearch.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        btnUserSearch.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnUserSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-search-18.png"))); // NOI18N
        btnUserSearch.setText("Tìm Kiếm");

        btnUserDelete.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnUserDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-delete-bin-18.png"))); // NOI18N
        btnUserDelete.setText("Xóa");
        btnUserDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDeleteActionPerformed(evt);
            }
        });

        btnUserUpdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnUserUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-update-18.png"))); // NOI18N
        btnUserUpdate.setText("Cập Nhật");
        btnUserUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserUpdateActionPerformed(evt);
            }
        });

        tblUser.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên Người Dùng", "Email", "Số Điện Thoại", "Role", "Ngày Tạo"
            }
        ));
        jScrollPane1.setViewportView(tblUser);

        btnUserRefresh.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnUserRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-renew-18.png"))); // NOI18N
        btnUserRefresh.setText("Làm Mới");
        btnUserRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnUserSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnUserUpdate)
                .addGap(28, 28, 28)
                .addComponent(btnUserDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUserRefresh)
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserSearch))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUserDelete)
                    .addComponent(btnUserUpdate)
                    .addComponent(btnUserRefresh))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Người Dùng", jPanel1);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thêm người dùng");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Mã Thủ Thư:");

        txtUserId.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Tên Thủ Thư:");

        txtUserName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Số Điện Thoại:");

        txtPhone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Role:");

        cboRole.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cboRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chọn", "Admin", "Thủ Thư" }));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Mật Khẩu:");

        pwdUserPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Xác Nhận Mật Khẩu:");

        pwdUserPasswordConfirm.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        btnAddUser.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-property-18.png"))); // NOI18N
        btnAddUser.setText("Thêm Mới");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnRefreshAddUser.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnRefreshAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-renew-18.png"))); // NOI18N
        btnRefreshAddUser.setText("Làm Mới");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhone)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(txtUserName)
                            .addComponent(pwdUserPassword)
                            .addComponent(txtUserId)
                            .addComponent(pwdUserPasswordConfirm))))
                .addGap(216, 216, 216))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefreshAddUser)
                .addGap(18, 18, 18)
                .addComponent(btnAddUser)
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pwdUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pwdUserPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddUser)
                    .addComponent(btnRefreshAddUser))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thêm Người Dùng", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
        if (txtUserId.getText().equals("") || txtUserName.getText().equals("") || txtPhone.getText().equals("") || pwdUserPassword.getPassword().equals("") || 
                pwdUserPasswordConfirm.getPassword().equals("") || txtEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Các trường không được để trống", "Lỗi", 0);
        }else if(cboRole.getSelectedItem().toString().equals("Chọn")){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn role cho người dùng", "Lỗi", 0);
        }else if(!Arrays.equals(pwdUserPassword.getPassword(), pwdUserPasswordConfirm.getPassword())){
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu và Xác nhận mật khẩu phải trùng nhau", "Lỗi", 0);
        }else{
            try {
                NguoiDung nd = new NguoiDung();
                LocalDate today = LocalDate.now();
                nd.setId(txtUserId.getText());
                nd.setTenNguoiDung(txtUserName.getText());
                nd.setEmail(txtEmail.getText());
                nd.setMatKhau(pwdUserPassword.getText());
                nd.setSdt(txtPhone.getText());
                nd.setRole(cboRole.getSelectedItem().toString());
                nd.setNgayTao(Date.valueOf(today));
                nguoiDungDAOImp.add(nd);
                JOptionPane.showMessageDialog(rootPane, "Thêm người dùng mới thành công", "Thông Báo", 1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Thêm người dùng mới không thành công", "Lỗi", 0);
                e.printStackTrace();
            }
         displayNguoiDung();
        }
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnUserUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserUpdateActionPerformed
        // TODO add your handling code here:
        TableModel model = tblUser.getModel();
        int selectedRow = tblUser.getSelectedRow();
        String id = model.getValueAt(selectedRow, 0).toString();
        String name = model.getValueAt(selectedRow, 1).toString();
        String email = model.getValueAt(selectedRow, 2).toString();
        String phone = model.getValueAt(selectedRow, 3).toString();
        String role = model.getValueAt(selectedRow, 4).toString();
        up.txtUserId.setText(id);
        up.txtUserName.setText(name);
        up.txtEmail.setText(email);
        up.txtPhone.setText(phone);
        if (role.equals("Admin")) {
            up.cboRole.setSelectedItem(role);
        }else if(role.equals("Thủ Thư")){
            up.cboRole.setSelectedItem(role);
        }
        up.setVisible(true);
    }//GEN-LAST:event_btnUserUpdateActionPerformed

    private void btnUserRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserRefreshActionPerformed
        // TODO add your handling code here:
        displayNguoiDung();
        JOptionPane.showMessageDialog(rootPane, "Danh sách đã được làm mới", "Thông Báo", 1);
    }//GEN-LAST:event_btnUserRefreshActionPerformed

    private void btnUserDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDeleteActionPerformed
        // TODO add your handling code here:
        int dialogConfirm = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa không?", "Thông báo", 0);
        if (dialogConfirm == JOptionPane.YES_OPTION) {
            nguoiDungDAOImp.remove(tblUser.getValueAt(tblUser.getSelectedRow(), 0).toString());
            JOptionPane.showMessageDialog(rootPane, "Xóa người dùng thành công", "Thông báo", 1);
            displayNguoiDung();
        }
    }//GEN-LAST:event_btnUserDeleteActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnRefreshAddUser;
    private javax.swing.JButton btnUserDelete;
    private javax.swing.JButton btnUserRefresh;
    private javax.swing.JButton btnUserSearch;
    private javax.swing.JButton btnUserUpdate;
    private javax.swing.JComboBox cboRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPasswordField pwdUserPassword;
    private javax.swing.JPasswordField pwdUserPasswordConfirm;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtUserSearch;
    // End of variables declaration//GEN-END:variables
}
