/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlythuvien;

import login.LoginSession;
import login.Login;
import com.bkap.dao.TheLoaiDAOImp;
import com.bkap.entities.TheLoai;
import com.bkap.util.SqlConnection;
import docgia.DocGiaIF;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import nhaxuatban.NhaXuatBanIF;
import phieumuon.PhieuMuonIF;
import sach.SachDetail;
import sach.SachIF;
import tacgia.TacGiaIF;
import theloai.CategoryUpdate;
import theloai.TheLoaiIF;
import thongke.ThongKeIF;
import user.UserIF;
import vitri.ViTriIF;

/**
 *
 * @author TaiyoNg
 */
public class MainFrame extends javax.swing.JFrame{
    private TheLoaiDAOImp theLoaiDAOImp;
    CategoryUpdate cu = new CategoryUpdate();

    /**
     * Creates new form MainFrame
     */
    
    LoginSession lgs;
    
    public MainFrame() {
        theLoaiDAOImp = new TheLoaiDAOImp();
        initComponents();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        pnlUserInfo = new javax.swing.JPanel();
        lblEmailTitle = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblNameTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblRoleTitle = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        pnlListMenu = new javax.swing.JPanel();
        btnBookType = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        btnAuthor = new javax.swing.JButton();
        btnPublisher = new javax.swing.JButton();
        btnReader = new javax.swing.JButton();
        btnRent = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnPlace = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm quản lý thư viện");
        getContentPane().setLayout(new java.awt.CardLayout());

        pnlMain.setPreferredSize(new java.awt.Dimension(1200, 630));

        pnlMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        pnlUserInfo.setBackground(new java.awt.Color(51, 51, 51));
        pnlUserInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Người Dùng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        pnlUserInfo.setForeground(new java.awt.Color(204, 204, 204));

        lblEmailTitle.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        lblEmailTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblEmailTitle.setText("ID:");

        lblID.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));

        lblNameTitle.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        lblNameTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblNameTitle.setText("Họ và tên:");

        lblName.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblRoleTitle.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        lblRoleTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblRoleTitle.setText("Role: ");

        lblRole.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 255, 255));
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout pnlUserInfoLayout = new javax.swing.GroupLayout(pnlUserInfo);
        pnlUserInfo.setLayout(pnlUserInfoLayout);
        pnlUserInfoLayout.setHorizontalGroup(
            pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlUserInfoLayout.createSequentialGroup()
                .addGroup(pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNameTitle)
                    .addComponent(lblEmailTitle)
                    .addComponent(lblRoleTitle))
                .addGap(18, 18, 18)
                .addGroup(pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlUserInfoLayout.setVerticalGroup(
            pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserInfoLayout.createSequentialGroup()
                .addComponent(lblEmailTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameTitle))
                .addGap(18, 18, 18)
                .addGroup(pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserInfoLayout.createSequentialGroup()
                        .addComponent(lblRoleTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        btnBookType.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBookType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/list.png"))); // NOI18N
        btnBookType.setText("Thể loại sách");
        btnBookType.setHideActionText(true);
        btnBookType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBookType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookTypeActionPerformed(evt);
            }
        });

        btnBook.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/open-book.png"))); // NOI18N
        btnBook.setText("Quản lý sách");
        btnBook.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        btnAuthor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAuthor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-pen-16.png"))); // NOI18N
        btnAuthor.setText("Quản lý tác giả");
        btnAuthor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorActionPerformed(evt);
            }
        });

        btnPublisher.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnPublisher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/publisher.png"))); // NOI18N
        btnPublisher.setText("Quản lý NXB");
        btnPublisher.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublisherActionPerformed(evt);
            }
        });

        btnReader.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnReader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-read-online-16.png"))); // NOI18N
        btnReader.setText("Quản lý độc giả");
        btnReader.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReaderActionPerformed(evt);
            }
        });

        btnRent.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnRent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-receipt-16.png"))); // NOI18N
        btnRent.setText("Quản lý phiếu mượn");
        btnRent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentActionPerformed(evt);
            }
        });

        btnReport.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-business-report-16.png"))); // NOI18N
        btnReport.setText("Báo cáo thống kê");
        btnReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-logout-rounded-down-16.png"))); // NOI18N
        btnLogout.setText("Đăng xuất");
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnPlace.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnPlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-book-shelf-16.png"))); // NOI18N
        btnPlace.setText("Quản lý vị trí sách");
        btnPlace.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceActionPerformed(evt);
            }
        });

        btnUser.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-user-male-16.png"))); // NOI18N
        btnUser.setText("Quản lý Người Dùng");
        btnUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlListMenuLayout = new javax.swing.GroupLayout(pnlListMenu);
        pnlListMenu.setLayout(pnlListMenuLayout);
        pnlListMenuLayout.setHorizontalGroup(
            pnlListMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBookType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPublisher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPlace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUser, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
            .addComponent(btnReader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlListMenuLayout.setVerticalGroup(
            pnlListMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListMenuLayout.createSequentialGroup()
                .addComponent(btnBookType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAuthor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPublisher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPlace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlListMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addComponent(pnlUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlListMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1152, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );

        getContentPane().add(pnlMain, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn đăng xuất?", "Đăng xuất", 2);
        if (result == JOptionPane.OK_OPTION) {
            new Login().setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBookTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookTypeActionPerformed
        // TODO add your handling code here:
        TheLoaiIF tlIF = new TheLoaiIF();
        jDesktopPane1.add(tlIF);
        tlIF.setVisible(true);
    }//GEN-LAST:event_btnBookTypeActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        SachIF saIF = new SachIF();
        jDesktopPane1.add(saIF);
        saIF.setVisible(true);
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorActionPerformed
        // TODO add your handling code here:
        TacGiaIF tgIF = new TacGiaIF();
        jDesktopPane1.add(tgIF);
        tgIF.setVisible(true);
    }//GEN-LAST:event_btnAuthorActionPerformed

    private void btnPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublisherActionPerformed
        // TODO add your handling code here:^
        NhaXuatBanIF nxbIF = new NhaXuatBanIF();
        jDesktopPane1.add(nxbIF);
        nxbIF.setVisible(true);
    }//GEN-LAST:event_btnPublisherActionPerformed

    private void btnReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReaderActionPerformed
        // TODO add your handling code here:
        DocGiaIF dgIF = new DocGiaIF();
        jDesktopPane1.add(dgIF);
        dgIF.setVisible(true);
    }//GEN-LAST:event_btnReaderActionPerformed

    private void btnRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentActionPerformed
        // TODO add your handling code here:
       PhieuMuonIF pmIF = new PhieuMuonIF();
       jDesktopPane1.add(pmIF);
       pmIF.setVisible(true);
    }//GEN-LAST:event_btnRentActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        ThongKeIF tkIF = new ThongKeIF();
        jDesktopPane1.add(tkIF);
        tkIF.setVisible(true);
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceActionPerformed
        // TODO add your handling code here:
        ViTriIF vtIF = new ViTriIF();
        jDesktopPane1.add(vtIF);
        vtIF.setVisible(true);
    }//GEN-LAST:event_btnPlaceActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        UserIF ndIF = new UserIF();
        jDesktopPane1.add(ndIF);
        ndIF.setVisible(true);
    }//GEN-LAST:event_btnUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuthor;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnBookType;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPlace;
    private javax.swing.JButton btnPublisher;
    private javax.swing.JButton btnReader;
    private javax.swing.JButton btnRent;
    private javax.swing.JButton btnReport;
    public javax.swing.JButton btnUser;
    public javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel lblEmailTitle;
    public javax.swing.JLabel lblID;
    public javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameTitle;
    public javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblRoleTitle;
    private javax.swing.JPanel pnlListMenu;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlUserInfo;
    // End of variables declaration//GEN-END:variables

 


}
