/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlythuvien;

import login.LoginSession;
import login.Login;
import com.bkap.dao.TheLoaiDAOImp;
import com.bkap.entities.TheLoai;
import com.bkap.util.SqlConnection;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import theloai.CategoryUpdate;

/**
 *
 * @author TaiyoNg
 */
public class MainFrame extends javax.swing.JFrame{
    private TheLoaiDAOImp theLoaiDAOImp;
    CategoryUpdate cu = new CategoryUpdate();
    /**
     * Creates new form MainFrame
     */
    CardLayout cl;
    LoginSession lgs;
    
    public MainFrame() {
        theLoaiDAOImp = new TheLoaiDAOImp();
        initComponents();
        cl = (CardLayout) pnlInfo.getLayout();
        lblEmail.setText(LoginSession.useremail);
        lblName.setText(LoginSession.username);
        lblRole.setText(LoginSession.userrole);
        

        displayCategory();
    }
    
    public void displayCategory(){
        List<TheLoai> data = theLoaiDAOImp.toList();
        DefaultTableModel model = (DefaultTableModel)tblCategory.getModel();
        model.setRowCount(0);
        for (TheLoai tl : data) {
            model.addRow(new Object[] {tl.getId(), tl.getTenTheLoai(), tl.isTrangThai(), tl.getNgayTao()});
        }
        tblCategory.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        pnlUserInfo = new javax.swing.JPanel();
        lblEmailTitle = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblNameTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblRoleTitle = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        pnlListMenu = new javax.swing.JPanel();
        btnControlPanel = new javax.swing.JButton();
        btnBookType = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        btnAuthor = new javax.swing.JButton();
        btnPublisher = new javax.swing.JButton();
        btnReader = new javax.swing.JButton();
        btnRent = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pnlInfo = new javax.swing.JPanel();
        pnlControlPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlBookType = new javax.swing.JPanel();
        tpnlBookType = new javax.swing.JTabbedPane();
        pnlCategoryList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategory = new javax.swing.JTable();
        txtCategorySearch = new javax.swing.JTextField();
        btnCategorySearch = new javax.swing.JButton();
        btnCategoryRefresh = new javax.swing.JButton();
        btnCategoryUpdate = new javax.swing.JButton();
        btnCategoryDelete = new javax.swing.JButton();
        lblCategoryTitle = new javax.swing.JLabel();
        pnlAddCategory = new javax.swing.JPanel();
        pnlBook = new javax.swing.JPanel();
        pnlAuthor = new javax.swing.JPanel();
        pnlPublisher = new javax.swing.JPanel();
        pnlReader = new javax.swing.JPanel();
        pnlRent = new javax.swing.JPanel();
        pnlReport = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm quản lý thư viện");
        setName("frame2"); // NOI18N
        getContentPane().setLayout(new java.awt.CardLayout());

        pnlMain.setPreferredSize(new java.awt.Dimension(1200, 630));

        lblEmailTitle.setText("Email:");

        lblNameTitle.setText("Họ và tên:");

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblRoleTitle.setText("Role: ");

        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout pnlUserInfoLayout = new javax.swing.GroupLayout(pnlUserInfo);
        pnlUserInfo.setLayout(pnlUserInfoLayout);
        pnlUserInfoLayout.setHorizontalGroup(
            pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlUserInfoLayout.createSequentialGroup()
                .addGroup(pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNameTitle)
                    .addComponent(lblEmailTitle)
                    .addComponent(lblRoleTitle))
                .addGap(18, 18, 18)
                .addGroup(pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlUserInfoLayout.setVerticalGroup(
            pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserInfoLayout.createSequentialGroup()
                .addComponent(lblEmailTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameTitle))
                .addGap(18, 18, 18)
                .addGroup(pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserInfoLayout.createSequentialGroup()
                        .addComponent(lblRoleTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        btnControlPanel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnControlPanel.setText("Bảng điều khiển");
        btnControlPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlPanelActionPerformed(evt);
            }
        });

        btnBookType.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnBookType.setText("Thể loại sách");
        btnBookType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookTypeActionPerformed(evt);
            }
        });

        btnBook.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnBook.setText("Quản lý sách");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        btnAuthor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAuthor.setText("Quản lý tác giả");
        btnAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorActionPerformed(evt);
            }
        });

        btnPublisher.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnPublisher.setText("Quản lý NXB");
        btnPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublisherActionPerformed(evt);
            }
        });

        btnReader.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnReader.setText("Quản lý độc giả");
        btnReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReaderActionPerformed(evt);
            }
        });

        btnRent.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRent.setText("Quản lý phiếu mượn");
        btnRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentActionPerformed(evt);
            }
        });

        btnReport.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnReport.setText("Báo cáo thống kê");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnLogout.setText("Đăng xuất");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlListMenuLayout = new javax.swing.GroupLayout(pnlListMenu);
        pnlListMenu.setLayout(pnlListMenuLayout);
        pnlListMenuLayout.setHorizontalGroup(
            pnlListMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBookType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPublisher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRent, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
            .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlListMenuLayout.setVerticalGroup(
            pnlListMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnControlPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBookType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAuthor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPublisher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlListMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addComponent(pnlUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlListMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlInfo.setLayout(new java.awt.CardLayout());

        pnlControlPanel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bảng điều khiển");

        javax.swing.GroupLayout pnlControlPanelLayout = new javax.swing.GroupLayout(pnlControlPanel);
        pnlControlPanel.setLayout(pnlControlPanelLayout);
        pnlControlPanelLayout.setHorizontalGroup(
            pnlControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControlPanelLayout.createSequentialGroup()
                .addContainerGap(352, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(432, 432, 432))
        );
        pnlControlPanelLayout.setVerticalGroup(
            pnlControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlPanelLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel2)
                .addContainerGap(448, Short.MAX_VALUE))
        );

        pnlInfo.add(pnlControlPanel, "pnlControlPanel");

        pnlBookType.setBackground(new java.awt.Color(255, 255, 255));

        pnlCategoryList.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        tblCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thể loại", "Tên thể loại", "Trạng thái", "Ngày tạo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCategory);

        txtCategorySearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnCategorySearch.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnCategorySearch.setText("Tìm kiếm");

        btnCategoryRefresh.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnCategoryRefresh.setText("Làm mới");
        btnCategoryRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryRefreshActionPerformed(evt);
            }
        });

        btnCategoryUpdate.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnCategoryUpdate.setText("Cập nhật");
        btnCategoryUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryUpdateActionPerformed(evt);
            }
        });

        btnCategoryDelete.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnCategoryDelete.setText("Xóa");

        lblCategoryTitle.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblCategoryTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCategoryTitle.setText("Thể loại sách");

        javax.swing.GroupLayout pnlCategoryListLayout = new javax.swing.GroupLayout(pnlCategoryList);
        pnlCategoryList.setLayout(pnlCategoryListLayout);
        pnlCategoryListLayout.setHorizontalGroup(
            pnlCategoryListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlCategoryListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCategoryListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCategoryListLayout.createSequentialGroup()
                        .addComponent(btnCategoryUpdate)
                        .addGap(41, 41, 41)
                        .addComponent(btnCategoryDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCategoryRefresh)
                        .addGap(30, 30, 30))
                    .addGroup(pnlCategoryListLayout.createSequentialGroup()
                        .addComponent(txtCategorySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCategorySearch)
                        .addContainerGap(450, Short.MAX_VALUE))))
            .addComponent(lblCategoryTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCategoryListLayout.setVerticalGroup(
            pnlCategoryListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoryListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCategoryTitle)
                .addGap(26, 26, 26)
                .addGroup(pnlCategoryListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCategorySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCategorySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(pnlCategoryListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCategoryRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCategoryUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCategoryDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        tpnlBookType.addTab("Danh sách thể loại\n", pnlCategoryList);

        javax.swing.GroupLayout pnlAddCategoryLayout = new javax.swing.GroupLayout(pnlAddCategory);
        pnlAddCategory.setLayout(pnlAddCategoryLayout);
        pnlAddCategoryLayout.setHorizontalGroup(
            pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 935, Short.MAX_VALUE)
        );
        pnlAddCategoryLayout.setVerticalGroup(
            pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        tpnlBookType.addTab("Thêm thể loại sách", pnlAddCategory);

        javax.swing.GroupLayout pnlBookTypeLayout = new javax.swing.GroupLayout(pnlBookType);
        pnlBookType.setLayout(pnlBookTypeLayout);
        pnlBookTypeLayout.setHorizontalGroup(
            pnlBookTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpnlBookType)
        );
        pnlBookTypeLayout.setVerticalGroup(
            pnlBookTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpnlBookType)
        );

        tpnlBookType.getAccessibleContext().setAccessibleName("Danh sách thể loại");

        pnlInfo.add(pnlBookType, "pnlBookType");

        pnlBook.setBackground(new java.awt.Color(204, 0, 102));

        javax.swing.GroupLayout pnlBookLayout = new javax.swing.GroupLayout(pnlBook);
        pnlBook.setLayout(pnlBookLayout);
        pnlBookLayout.setHorizontalGroup(
            pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        pnlBookLayout.setVerticalGroup(
            pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );

        pnlInfo.add(pnlBook, "pnlBook");

        javax.swing.GroupLayout pnlAuthorLayout = new javax.swing.GroupLayout(pnlAuthor);
        pnlAuthor.setLayout(pnlAuthorLayout);
        pnlAuthorLayout.setHorizontalGroup(
            pnlAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        pnlAuthorLayout.setVerticalGroup(
            pnlAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );

        pnlInfo.add(pnlAuthor, "pnlAuthor");

        javax.swing.GroupLayout pnlPublisherLayout = new javax.swing.GroupLayout(pnlPublisher);
        pnlPublisher.setLayout(pnlPublisherLayout);
        pnlPublisherLayout.setHorizontalGroup(
            pnlPublisherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        pnlPublisherLayout.setVerticalGroup(
            pnlPublisherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );

        pnlInfo.add(pnlPublisher, "pnlPublisher");

        javax.swing.GroupLayout pnlReaderLayout = new javax.swing.GroupLayout(pnlReader);
        pnlReader.setLayout(pnlReaderLayout);
        pnlReaderLayout.setHorizontalGroup(
            pnlReaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        pnlReaderLayout.setVerticalGroup(
            pnlReaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );

        pnlInfo.add(pnlReader, "pnlReader");

        javax.swing.GroupLayout pnlRentLayout = new javax.swing.GroupLayout(pnlRent);
        pnlRent.setLayout(pnlRentLayout);
        pnlRentLayout.setHorizontalGroup(
            pnlRentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        pnlRentLayout.setVerticalGroup(
            pnlRentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );

        pnlInfo.add(pnlRent, "pnlRent");

        javax.swing.GroupLayout pnlReportLayout = new javax.swing.GroupLayout(pnlReport);
        pnlReport.setLayout(pnlReportLayout);
        pnlReportLayout.setHorizontalGroup(
            pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        pnlReportLayout.setVerticalGroup(
            pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );

        pnlInfo.add(pnlReport, "pnlReport");

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pnlMain, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn đăng xuất?", "Đăng xuất", 2);
        if (result == JOptionPane.OK_OPTION) {
            new Login().setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnControlPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlPanelActionPerformed
        // TODO add your handling code here:
        cl.show(pnlInfo, "pnlControlPanel");
    }//GEN-LAST:event_btnControlPanelActionPerformed

    private void btnBookTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookTypeActionPerformed
        // TODO add your handling code here:
        cl.show(pnlInfo, "pnlBookType");
    }//GEN-LAST:event_btnBookTypeActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        cl.show(pnlInfo, "pnlBook");
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorActionPerformed
        // TODO add your handling code here:
        cl.show(pnlInfo, "pnlAuthor");
    }//GEN-LAST:event_btnAuthorActionPerformed

    private void btnPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublisherActionPerformed
        // TODO add your handling code here:
        cl.show(pnlInfo, "pnlPublisher");
    }//GEN-LAST:event_btnPublisherActionPerformed

    private void btnReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReaderActionPerformed
        // TODO add your handling code here:
        cl.show(pnlInfo, "pnlReader");
    }//GEN-LAST:event_btnReaderActionPerformed

    private void btnRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentActionPerformed
        // TODO add your handling code here:
        cl.show(pnlInfo, "pnlRent");
    }//GEN-LAST:event_btnRentActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        cl.show(pnlInfo, "pnlReport");
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnCategoryRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryRefreshActionPerformed
        // TODO add your handling code here:
        displayCategory();
    }//GEN-LAST:event_btnCategoryRefreshActionPerformed

    private void tblCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoryMouseClicked
        // TODO add your handling code here:
        int index = tblCategory.getSelectedRow();
        TableModel model = tblCategory.getModel();
        String id = model.getValueAt(index, 0).toString();
        String categoryName = model.getValueAt(index, 1).toString();
        Boolean categoryStatus = (Boolean) model.getValueAt(index, 2);
        
        cu.pack();
        cu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        cu.txtCategoryId.setText(id);
        cu.txtCategoryName.setText(categoryName);
        cu.chbCategoryStatus.setSelected(categoryStatus); 
    }//GEN-LAST:event_tblCategoryMouseClicked

    private void btnCategoryUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryUpdateActionPerformed
        // TODO add your handling code here:
        cu.setVisible(true);
    }//GEN-LAST:event_btnCategoryUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuthor;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnBookType;
    private javax.swing.JButton btnCategoryDelete;
    private javax.swing.JButton btnCategoryRefresh;
    private javax.swing.JButton btnCategorySearch;
    private javax.swing.JButton btnCategoryUpdate;
    private javax.swing.JButton btnControlPanel;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPublisher;
    private javax.swing.JButton btnReader;
    private javax.swing.JButton btnRent;
    private javax.swing.JButton btnReport;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoryTitle;
    public javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailTitle;
    public javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameTitle;
    public javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblRoleTitle;
    private javax.swing.JPanel pnlAddCategory;
    private javax.swing.JPanel pnlAuthor;
    private javax.swing.JPanel pnlBook;
    private javax.swing.JPanel pnlBookType;
    private javax.swing.JPanel pnlCategoryList;
    private javax.swing.JPanel pnlControlPanel;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlListMenu;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPublisher;
    private javax.swing.JPanel pnlReader;
    private javax.swing.JPanel pnlRent;
    private javax.swing.JPanel pnlReport;
    private javax.swing.JPanel pnlUserInfo;
    private javax.swing.JTable tblCategory;
    private javax.swing.JTabbedPane tpnlBookType;
    private javax.swing.JTextField txtCategorySearch;
    // End of variables declaration//GEN-END:variables


}
