/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhaxuatban;
import com.bkap.dao.NhaXuatBanDAOImp;
import com.bkap.entities.NhaXuatBan;
import java.awt.Color;
import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author NAM_STD
 */
public class NhaXuatBanIF extends javax.swing.JInternalFrame implements NhaXuatBanUpdate.CallBackUpdateNXB{
    NhaXuatBanDAOImp nhaXuatBanDAOImp;
    NhaXuatBanUpdate pu = new NhaXuatBanUpdate(this);
    /**
     * Creates new form NhaXuatBanIF
     */
    public NhaXuatBanIF() {
        nhaXuatBanDAOImp = new NhaXuatBanDAOImp();      
        initComponents();
        //Bắt sự kiện khi thay đổi lựa chọn trên jTable
        tblPublisher.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                
            }
        });
        displayNhaXuatBan();

    }

    private void displayNhaXuatBan(){
        List<NhaXuatBan> data = nhaXuatBanDAOImp.toList();
        
        DefaultTableModel model = (DefaultTableModel)tblPublisher.getModel();
        //Xoa bo du ieu cu de addRow ko trung lap
        model.setRowCount(0);
        TableRowSorter <DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tblPublisher.setRowSorter(tr);
        tr.setRowFilter(null);
        for (NhaXuatBan nxb : data) {
            model.addRow(new Object[] {nxb.getId(), nxb.getTenNXB(), nxb.getNgayTao()});
        }
        tblPublisher.setModel(model);
    }
    public void updateNXB(String id, String name){
        NhaXuatBan nxb = new NhaXuatBan();
        nxb.setId(id);
        nxb.setTenNXB(name);
        nhaXuatBanDAOImp.edit(nxb);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPublisherSreach = new javax.swing.JButton();
        txtPublisherSreach = new javax.swing.JTextField();
        btnPublisherUpdate = new javax.swing.JButton();
        btnPublisherDelete = new javax.swing.JButton();
        btnPublisherRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPublisher = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAddPublisherId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAddPublisherName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnAddNewPublisher = new javax.swing.JButton();
        lblIdErr = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Quản Lý Nhà Xuất Bản");

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhà Xuất Bản");

        btnPublisherSreach.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnPublisherSreach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-search-18.png"))); // NOI18N
        btnPublisherSreach.setText("Tìm kiếm");
        btnPublisherSreach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublisherSreachActionPerformed(evt);
            }
        });

        txtPublisherSreach.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        btnPublisherUpdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnPublisherUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-update-18.png"))); // NOI18N
        btnPublisherUpdate.setText("Cập nhật");
        btnPublisherUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublisherUpdateActionPerformed(evt);
            }
        });

        btnPublisherDelete.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnPublisherDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-delete-bin-18.png"))); // NOI18N
        btnPublisherDelete.setText("Xóa");
        btnPublisherDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublisherDeleteActionPerformed(evt);
            }
        });

        btnPublisherRefresh.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnPublisherRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-renew-18.png"))); // NOI18N
        btnPublisherRefresh.setText("Làm mới");
        btnPublisherRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublisherRefreshActionPerformed(evt);
            }
        });

        tblPublisher.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tblPublisher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tên NXB", "Ngày Tạo"
            }
        ));
        jScrollPane1.setViewportView(tblPublisher);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPublisherSreach, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPublisherSreach)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPublisherUpdate)
                        .addGap(68, 68, 68)
                        .addComponent(btnPublisherDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPublisherRefresh)
                        .addGap(98, 98, 98))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPublisherSreach)
                    .addComponent(txtPublisherSreach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPublisherUpdate)
                    .addComponent(btnPublisherDelete)
                    .addComponent(btnPublisherRefresh))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nhà Xuất Bản", jPanel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thêm mới Nhà Xuất Bản");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Mã Nhà Xuất Bản : ");

        txtAddPublisherId.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtAddPublisherId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddPublisherIdKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Tên Nhà Xuất Bản :");

        txtAddPublisherName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-renew-18.png"))); // NOI18N
        jButton1.setText("Làm mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnAddNewPublisher.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAddNewPublisher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-property-18.png"))); // NOI18N
        btnAddNewPublisher.setText("Thêm mới");
        btnAddNewPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewPublisherActionPerformed(evt);
            }
        });

        lblIdErr.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblIdErr.setForeground(new java.awt.Color(252, 9, 31));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jButton1)
                .addGap(66, 66, 66)
                .addComponent(btnAddNewPublisher)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblIdErr, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddPublisherId)
                            .addComponent(txtAddPublisherName, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))))
                .addGap(154, 154, 154))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAddPublisherId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(lblIdErr, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAddPublisherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnAddNewPublisher))
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thêm mới Nhà Xuất Bản", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewPublisherActionPerformed
        
        int choice = JOptionPane.showConfirmDialog(this, "Bạn muốn thêm mới không?","Hỏi",JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        }
        
        StringBuilder sb = new StringBuilder();     
        
        if(txtAddPublisherId.getText().equals("")){
            sb.append("Mã Nhà Xuất Bản Không Được Để Trống\n");
            if (sb.length()>=0) {
            JOptionPane.showMessageDialog(this, sb.toString(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
        }else if(txtAddPublisherName.getText().equals("")){
            sb.append("Tên Nhà Xuất Bản Không Được Để Trống");
            if (sb.length()>=0) {
            JOptionPane.showMessageDialog(this, sb.toString(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
        }else{
            NhaXuatBan nxb = new NhaXuatBan();
            LocalDate today = LocalDate.now();
            nxb.setId(txtAddPublisherId.getText());
            nxb.setTenNXB(txtAddPublisherName.getText());
            nxb.setNgayTao(Date.valueOf(today));
            nhaXuatBanDAOImp.add(nxb);
            displayNhaXuatBan();
            JOptionPane.showMessageDialog(this, "Thêm mới thành công");
        }

        
    }//GEN-LAST:event_btnAddNewPublisherActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtAddPublisherId.setText("");
        txtAddPublisherName.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPublisherRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublisherRefreshActionPerformed
        txtPublisherSreach.setText("");
    }//GEN-LAST:event_btnPublisherRefreshActionPerformed

    private void btnPublisherDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublisherDeleteActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa thông tin không?","Hỏi",JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            int selectedRow = tblPublisher.getSelectedRow();
            TableModel model = tblPublisher.getModel();
            String id = model.getValueAt(selectedRow, 0).toString();
            nhaXuatBanDAOImp.remove(id);
            JOptionPane.showMessageDialog(this, "Xóa thành công", "Success", 1);
            displayNhaXuatBan();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error", "Error", 0);
        }
    }//GEN-LAST:event_btnPublisherDeleteActionPerformed

    private void btnPublisherUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublisherUpdateActionPerformed
        TableModel model = tblPublisher.getModel();
        int selectedRow = tblPublisher.getSelectedRow();
        String id = model.getValueAt(selectedRow, 0).toString();
        String name = model.getValueAt(selectedRow, 1).toString();
        pu.txtPublisherId.setText(id);
        pu.txtPublisherName.setText(name);
        pu.setVisible(true);
    }//GEN-LAST:event_btnPublisherUpdateActionPerformed

    private void btnPublisherSreachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublisherSreachActionPerformed
        // TODO add your handling code here:
        if (txtPublisherSreach.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Cần nhập thông tin để tìm kiếm !");
            return;
        }
        
        try {
            DefaultTableModel table = (DefaultTableModel)tblPublisher.getModel();
            String search = txtPublisherSreach.getText();
            TableRowSorter <DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
            tblPublisher.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(search));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error" + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPublisherSreachActionPerformed

    private void txtAddPublisherIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddPublisherIdKeyReleased
        // TODO add your handling code here:
        String pattern = "^XB[0-9]{3}$";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(txtAddPublisherId.getText());
        if(!match.matches()){
            lblIdErr.setText("Mã Nhà Xuất Bản phải có 5 ký tự và theo định dạng XBxxx (x là số)");
        }else{
            lblIdErr.setText("");
        }
    }//GEN-LAST:event_txtAddPublisherIdKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewPublisher;
    private javax.swing.JButton btnPublisherDelete;
    private javax.swing.JButton btnPublisherRefresh;
    private javax.swing.JButton btnPublisherSreach;
    private javax.swing.JButton btnPublisherUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblIdErr;
    private javax.swing.JTable tblPublisher;
    private javax.swing.JTextField txtAddPublisherId;
    private javax.swing.JTextField txtAddPublisherName;
    private javax.swing.JTextField txtPublisherSreach;
    // End of variables declaration//GEN-END:variables

    @Override
    public void doUpdateNXB(String id, String name) {
        try {
            updateNXB(id, name);
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin NXB thành công", "Thông Báo", 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin NXB không thành công", "Lỗi", 0);
            e.printStackTrace();
        }
        displayNhaXuatBan();
    }
}
