/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phieumuon;

import com.bkap.dao.DocGiaDAOImp;
import com.bkap.dao.PhieuMuonDAOImp;
import com.bkap.dao.PhieuMuonSachDAOImp;
import com.bkap.dao.SachDAOImp;
import com.bkap.entities.DocGia;
import com.bkap.entities.PhieuMuon;
import com.bkap.entities.PhieuMuonSach;
import com.bkap.entities.Sach;
import java.sql.Date;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author TaiyoNg
 */
public class PhieuMuonIF extends javax.swing.JInternalFrame {
    DocGiaDAOImp docGiaDAOImp;
    SachDAOImp sachDAOImp;
    PhieuMuonDAOImp phieuMuonDAOImp;
    PhieuMuonSachDAOImp phieuMuonSachDAOImp;
    /**
     * Creates new form PhieuMuonIF
     */
    public PhieuMuonIF() {
        sachDAOImp = new SachDAOImp();
        docGiaDAOImp = new DocGiaDAOImp();
        phieuMuonDAOImp = new PhieuMuonDAOImp();
        phieuMuonSachDAOImp = new PhieuMuonSachDAOImp();
        initComponents();
        displayBooks();
        loadCbo();
    }
    
    public void loadCbo(){
        List<DocGia> dgdata = docGiaDAOImp.toList();
        for (DocGia dg : dgdata) {
            cboReaderId.addItem(dg);
        }
        
    }
    public void displayBooks() {
        List<Sach> sadata = sachDAOImp.toList();
        DefaultTableModel model = (DefaultTableModel) tblBookList.getModel();
        model.setRowCount(0);
        String trangThai;
        for (Sach sa : sadata) {
            if (sa.isTrangThai() == true) {
                trangThai = "Còn Sách";
            }else{
                trangThai = "Hết Sách";
            }
            model.addRow(new Object[]{sa.getId(), sa.getTenSach(), sa.getButDanh(), trangThai});
        }
        tblBookList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblReaderName = new javax.swing.JLabel();
        lblReaderEmail = new javax.swing.JLabel();
        lblReaderPhone = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboReaderId = new javax.swing.JComboBox();
        btnGetReader = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtBookSearch = new javax.swing.JTextField();
        btnBookSearch = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBookList = new javax.swing.JTable();
        btnBookChoose = new javax.swing.JButton();
        btnBookSearch1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBookChoose = new javax.swing.JTable();
        btnBookChooseDelete = new javax.swing.JButton();
        btnCreateRent = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Người đọc");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel2.setText("Họ và tên:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel3.setText("Email:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel4.setText("Số điện thoại:");

        lblReaderName.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        lblReaderEmail.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        lblReaderPhone.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel8.setText("ID người đọc:");

        cboReaderId.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        btnGetReader.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnGetReader.setText("Lấy Thông Tin");
        btnGetReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetReaderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReaderName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblReaderEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblReaderPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(cboReaderId, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGetReader)))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboReaderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetReader))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblReaderName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addComponent(lblReaderEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblReaderPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtBookSearch.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        btnBookSearch.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnBookSearch.setText("Tìm");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sách");

        tblBookList.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tblBookList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Sách", "Tên Sách", "Tác Giả", "Trạng Thái"
            }
        ));
        tblBookList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBookListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBookList);

        btnBookChoose.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnBookChoose.setText("Chọn Sách");
        btnBookChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookChooseActionPerformed(evt);
            }
        });

        btnBookSearch1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(txtBookSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBookSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBookChoose)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(251, 251, 251)
                    .addComponent(btnBookSearch1)
                    .addContainerGap(262, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBookSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBookSearch)
                    .addComponent(btnBookChoose))
                .addGap(194, 194, 194))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jLabel6)
                    .addContainerGap(243, Short.MAX_VALUE)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(102, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(btnBookSearch1)
                    .addContainerGap(184, Short.MAX_VALUE)))
        );

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sách đã chọn");

        tblBookChoose.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tblBookChoose.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách"
            }
        ));
        jScrollPane1.setViewportView(tblBookChoose);

        btnBookChooseDelete.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnBookChooseDelete.setText("Xóa Sách");
        btnBookChooseDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookChooseDeleteActionPerformed(evt);
            }
        });

        btnCreateRent.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnCreateRent.setText("Tạo Phiếu Mượn");
        btnCreateRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreateRent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBookChooseDelete)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBookChooseDelete)
                    .addComponent(btnCreateRent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setText("Test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mượn Sách", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thống Kê Phiếu Mượn", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Trả Sách", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBookListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBookListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBookListMouseClicked

    private void btnBookChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookChooseActionPerformed
        // TODO add your handling code here:
        TableModel model1 = tblBookList.getModel();
        int[] indexs = tblBookList.getSelectedRows();
        Object[] rows = new Object[2];
        DefaultTableModel model2 = (DefaultTableModel) tblBookChoose.getModel();
        for (int i = 0; i < indexs.length; i++) {
            rows[0] = model1.getValueAt(indexs[i], 0);
            rows[1] = model1.getValueAt(indexs[i], 1);
            model2.addRow(rows);
        }
    }//GEN-LAST:event_btnBookChooseActionPerformed

    private void btnBookChooseDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookChooseDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblBookChoose.getModel();
        if (tblBookChoose.getSelectedRowCount() == 1) {
            model.removeRow(tblBookChoose.getSelectedRow());
        } else {
            if (tblBookChoose.getSelectedRowCount() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Bảng đã trống", "Thông báo", 3);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn một dòng trong bảng", "Lỗi", 0);
            }
        }
    }//GEN-LAST:event_btnBookChooseDeleteActionPerformed

    private void btnCreateRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRentActionPerformed
        // TODO add your handling code here:
        if (tblBookChoose.getRowCount() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Bảng hiện đang trống", "Lỗi", 0);
        }else{
            try {
                PhieuMuon pm = new PhieuMuon();
                LocalDate today = LocalDate.now();
                int tienMuon = 0;
                DefaultTableModel model = (DefaultTableModel) tblBookChoose.getModel();
                for (int i = 0; i < model.getRowCount(); i++) {
                    Sach sa = sachDAOImp.find((String) model.getValueAt(i, 0));
                    tienMuon = (int) (tienMuon + sa.getGiaMuon());
                }
                pm.setIdDocGia(((DocGia) cboReaderId.getSelectedItem()).getId());
                pm.setSoLuongMuon(tblBookChoose.getRowCount());
                pm.setNgayMuon(Date.valueOf(today));
                pm.setHanTra(Date.valueOf(today.plusDays(20)));
                pm.setTongTien(tienMuon);
                pm.setTrangThai(false);
                pm.setNgayTao(Date.valueOf(today));
                phieuMuonDAOImp.add(pm);

                PhieuMuonSach pms = new PhieuMuonSach();
                for (int i = 0; i < model.getRowCount(); i++) {
                    Sach sa = sachDAOImp.find((String) model.getValueAt(i, 0));
                    pms.setIdPhieuMuon(pm.getId());
                    pms.setIdSach(sa.getId());
                    pms.setNgayTra(null);
                    phieuMuonSachDAOImp.add(pms);
                }
                JOptionPane.showMessageDialog(rootPane, "Tạo phiếu mượn thành công", "Thông báo", 1);
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, "Đã có lỗi xảy ra", "Lỗi", 0);
            }
        }
    }//GEN-LAST:event_btnCreateRentActionPerformed

    private void btnGetReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetReaderActionPerformed
        // TODO add your handling code here:
        String id = ((DocGia)cboReaderId.getSelectedItem()).getId();
        DocGia dg = docGiaDAOImp.find(id);
        lblReaderName.setText(dg.getTenDocGia());
        lblReaderEmail.setText(dg.getEmail());
        lblReaderPhone.setText(dg.getSdt());
    }//GEN-LAST:event_btnGetReaderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblBookChoose.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                Sach sa = sachDAOImp.find((String) model.getValueAt(i, 0));
                JOptionPane.showMessageDialog(rootPane, sa.getId());
            }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookChoose;
    private javax.swing.JButton btnBookChooseDelete;
    private javax.swing.JButton btnBookSearch;
    private javax.swing.JButton btnBookSearch1;
    private javax.swing.JButton btnCreateRent;
    private javax.swing.JButton btnGetReader;
    private javax.swing.JComboBox cboReaderId;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblReaderEmail;
    private javax.swing.JLabel lblReaderName;
    private javax.swing.JLabel lblReaderPhone;
    private javax.swing.JTable tblBookChoose;
    private javax.swing.JTable tblBookList;
    private javax.swing.JTextField txtBookSearch;
    // End of variables declaration//GEN-END:variables
}
