/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phieumuon;

import com.bkap.dao.PhieuMuonDAOImp;
import com.bkap.dao.PhieuMuonSachDAOImp;
import com.bkap.dao.SachDAOImp;
import com.bkap.entities.PhieuMuon;
import com.bkap.entities.PhieuMuonSach;
import com.bkap.entities.Sach;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author TaiyoNg
 */
public class RentCardDetail extends javax.swing.JFrame implements ReturnForm.CallbackReturnBook{

    SachDAOImp sachDAOImp;
    PhieuMuonDAOImp phieuMuonDAOImp;
    PhieuMuonSachDAOImp phieuMuonSachDAOImp;
    SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    ReturnForm rf = new ReturnForm(this);
    CallbackRentStatus cbrs;

    
    interface CallbackRentStatus{
        public void doRentStatus(int idPhieuMuon);
        public void doBookStatus(String tenSach, boolean viPham, String chiTietViPham);
    }

    public RentCardDetail(CallbackRentStatus cbrs) {
        sachDAOImp = new SachDAOImp();
        phieuMuonDAOImp = new PhieuMuonDAOImp();
        phieuMuonSachDAOImp = new PhieuMuonSachDAOImp();
        initComponents();
        this.cbrs = cbrs;
    }
    /**
     * Creates new form RentCardDetail
     */
    
    
    public RentCardDetail() {
        sachDAOImp = new SachDAOImp();
        phieuMuonDAOImp = new PhieuMuonDAOImp();
        phieuMuonSachDAOImp = new PhieuMuonSachDAOImp();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void displayRentBook(){
        List<PhieuMuonSach> pmsdata = phieuMuonSachDAOImp.findBook(Integer.parseInt(lblRentId.getText()));
        DefaultTableModel bmodel = (DefaultTableModel) tblRentedBook.getModel();
        bmodel.setRowCount(0);
        String tinhTrang;
        for (PhieuMuonSach pmsl : pmsdata) {
            if (pmsl.getNgayTra() == null) {
                tinhTrang = "Chưa Trả";
            }else{
                tinhTrang = "Đã Trả";
            }
            bmodel.addRow(new Object[]{pmsl.getIdSach(), pmsl.getTenSach(), pmsl.getButDanh(), pmsl.getTenNXB(), tinhTrang});
        }
        tblRentedBook.setModel(bmodel);
    }
    public void updateRentStatus(int idPhieuMuon, String idSach, Date ngayTra){
        PhieuMuonSach pms = phieuMuonSachDAOImp.findSingle(idPhieuMuon, idSach);
        pms.setNgayTra(ngayTra);
        phieuMuonSachDAOImp.edit(pms);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblRentDate = new javax.swing.JLabel();
        lblReaderEmail = new javax.swing.JLabel();
        lblReaderBirthday = new javax.swing.JLabel();
        lblReaderPhone = new javax.swing.JLabel();
        lblReaderId = new javax.swing.JLabel();
        lblRentId = new javax.swing.JLabel();
        lblReaderName = new javax.swing.JLabel();
        lblReturnDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRentedBook = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        btnReturnBook = new javax.swing.JButton();
        btnReturnBookRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chi Tiết Phiếu Mượn");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Phiếu Mượn Sách");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel2.setText("Mã Phiếu Mượn:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel3.setText("Số Điện Thoại:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel4.setText("Ngày Sinh:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel5.setText("Tên Độc GIả:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel6.setText("Mã Độc Giả:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel7.setText("Email:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel8.setText("Ngày Mượn:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel9.setText("Hạn Trả Sách:");

        lblRentDate.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        lblReaderEmail.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        lblReaderBirthday.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        lblReaderPhone.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        lblReaderId.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        lblRentId.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        lblReaderName.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        lblReturnDate.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        tblRentedBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách", "Tác Giả", "Nhà Xuất Bản", "Trạng Thái"
            }
        ));
        jScrollPane1.setViewportView(tblRentedBook);

        jLabel12.setFont(new java.awt.Font("Arial", 3, 15)); // NOI18N
        jLabel12.setText("Thông tin sách đã mượn:");

        btnReturnBook.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnReturnBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-return-book-16.png"))); // NOI18N
        btnReturnBook.setText("Trả Sách");
        btnReturnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnBookActionPerformed(evt);
            }
        });

        btnReturnBookRefresh.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnReturnBookRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-renew-18.png"))); // NOI18N
        btnReturnBookRefresh.setText("Làm Mới");
        btnReturnBookRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnBookRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblReaderPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRentId, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblReaderBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblReaderId, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblReaderEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblReaderName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReturnBookRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReturnBook)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblRentId, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6))
                    .addComponent(lblReaderId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReaderName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lblReaderBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblReaderPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lblReaderEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lblRentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(lblReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(btnReturnBook)
                    .addComponent(btnReturnBookRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnBookActionPerformed
        // TODO add your handling code here:
        TableModel model = tblRentedBook.getModel();
        int selectedRow = tblRentedBook.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(rootPane, "Xin mời chọn sách muốn trả", "Thông Báo", 2);
        } else {
            if (model.getValueAt(selectedRow, 4) == "Đã Trả") {
                JOptionPane.showMessageDialog(rootPane, "Sách đã trả không thể trả lần nữa", "Lỗi", 0);
            } else {
                Sach sa = sachDAOImp.find(model.getValueAt(selectedRow, 0).toString());
                PhieuMuon pm = phieuMuonDAOImp.find(Integer.parseInt(lblRentId.getText()));
                LocalDate today = LocalDate.now();
                rf.txtReturnDate.setText(String.valueOf(today));
                rf.lblBookName.setText(model.getValueAt(selectedRow, 1).toString());
                rf.lblRentId.setText(String.valueOf(pm.getId()));
                rf.lblReaderId.setText(lblReaderId.getText());
                if (pm.getHanTra().before(Date.valueOf(today))) {
                    JOptionPane.showMessageDialog(rootPane, "Sách " + sa.getTenSach() + " đã quá hạn trả sách", "Thông Báo", 2);
                    rf.chbViolation.setSelected(true);
                }
                rf.setVisible(true);
            }

        }

    }//GEN-LAST:event_btnReturnBookActionPerformed

    private void btnReturnBookRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnBookRefreshActionPerformed
        // TODO add your handling code here:
        displayRentBook();
    }//GEN-LAST:event_btnReturnBookRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentCardDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentCardDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentCardDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentCardDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentCardDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturnBook;
    private javax.swing.JButton btnReturnBookRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblReaderBirthday;
    public javax.swing.JLabel lblReaderEmail;
    public javax.swing.JLabel lblReaderId;
    public javax.swing.JLabel lblReaderName;
    public javax.swing.JLabel lblReaderPhone;
    public javax.swing.JLabel lblRentDate;
    public javax.swing.JLabel lblRentId;
    public javax.swing.JLabel lblReturnDate;
    public javax.swing.JTable tblRentedBook;
    // End of variables declaration//GEN-END:variables

    @Override
    public void doReturnBook(int idPhieuMuon, String idSach, Date ngayTra) {
        updateRentStatus(idPhieuMuon, idSach, ngayTra);
        displayRentBook();
    }
    
    @Override
    public void doRentStatus(int idPhieuMuon) {
        cbrs.doRentStatus(idPhieuMuon);
    }

    @Override
    public void doBookStatus(String tenSach, boolean viPham, String chiTietViPham) {
        cbrs.doBookStatus(tenSach, viPham, chiTietViPham);
    }
}
