/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vitri;

import com.bkap.dao.ViTriDAOImp;
import com.bkap.entities.ViTri;
import com.sun.java.accessibility.util.SwingEventMonitor;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author NAM_STD
 */
public class ViTriIF extends javax.swing.JInternalFrame implements ViTriUpdate.CallbackUpdateViTri{
    ViTriDAOImp viTriDAOImp;
    ViTriUpdate lu = new ViTriUpdate(this);
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    /**
     * Creates new form ViTriIF
     */
    public ViTriIF() {
        viTriDAOImp = new ViTriDAOImp();
        initComponents();
        tblLocation.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                
            }
        });
        displayViTri();
    }

    
    private void displayViTri(){
        List<ViTri> data = viTriDAOImp.toList();
        DefaultTableModel model = (DefaultTableModel)tblLocation.getModel();
        TableRowSorter <DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tblLocation.setRowSorter(tr);
        tr.setRowFilter(null);
        Calendar c = Calendar.getInstance();
        model.setRowCount(0);
        for (ViTri vt : data) {
            c.setTime(vt.getNgayTao());
            c.add(Calendar.DATE, 2);
            model.addRow(new Object[] {vt.getId(), vt.getTenViTri(), sdf.format(c.getTime())});
        }
        tblLocation.setModel(model);
    }
    private void updateViTri(String id, String name){
        StringBuilder sb = new StringBuilder();     
        
        if(id.equals("")||name.equals("")){
            sb.append("Không được để trống!");
            if (sb.length()>=0) {
            JOptionPane.showMessageDialog(this, sb.toString(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
        }else{
            ViTri vtUp = new ViTri();
            vtUp.setId(id);
            vtUp.setTenViTri(name);
            viTriDAOImp.edit(vtUp);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtLocationSreach = new javax.swing.JTextField();
        btnLocationSreach = new javax.swing.JButton();
        btnLocationUpdate = new javax.swing.JButton();
        btnLocationDelete = new javax.swing.JButton();
        btnLocationRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLocation = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAddLocationId = new javax.swing.JTextField();
        txtAddLocationName = new javax.swing.JTextField();
        btnAddLocationRefresh = new javax.swing.JButton();
        btnAddNewLocation = new javax.swing.JButton();
        lblIdErr = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Quản Lý Vị Trí Sách");

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vị Trí Sách");

        txtLocationSreach.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        btnLocationSreach.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLocationSreach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-search-18.png"))); // NOI18N
        btnLocationSreach.setText("Tìm kiếm");
        btnLocationSreach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocationSreachActionPerformed(evt);
            }
        });

        btnLocationUpdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLocationUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-update-18.png"))); // NOI18N
        btnLocationUpdate.setText("Cập nhật");
        btnLocationUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocationUpdateActionPerformed(evt);
            }
        });

        btnLocationDelete.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLocationDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-delete-bin-18.png"))); // NOI18N
        btnLocationDelete.setText("Xóa");
        btnLocationDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocationDeleteActionPerformed(evt);
            }
        });

        btnLocationRefresh.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLocationRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-renew-18.png"))); // NOI18N
        btnLocationRefresh.setText("Làm mới");
        btnLocationRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocationRefreshActionPerformed(evt);
            }
        });

        tblLocation.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tblLocation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Vị trí", "Ngày tạo"
            }
        ));
        jScrollPane1.setViewportView(tblLocation);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLocationSreach, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLocationUpdate))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLocationSreach)
                        .addContainerGap(175, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLocationDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLocationRefresh)
                        .addGap(43, 43, 43))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocationSreach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLocationSreach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLocationUpdate)
                    .addComponent(btnLocationDelete)
                    .addComponent(btnLocationRefresh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vị trí", jPanel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thêm mới vị trí");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setText("Mã Vị Trí :");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setText("Tên Vị Trí :");

        txtAddLocationId.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        txtAddLocationName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        btnAddLocationRefresh.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnAddLocationRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-renew-18.png"))); // NOI18N
        btnAddLocationRefresh.setText("Làm mới");
        btnAddLocationRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLocationRefreshActionPerformed(evt);
            }
        });

        btnAddNewLocation.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnAddNewLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-property-18.png"))); // NOI18N
        btnAddNewLocation.setText("Thêm mới");
        btnAddNewLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewLocationActionPerformed(evt);
            }
        });

        lblIdErr.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblIdErr.setForeground(new java.awt.Color(252, 9, 31));
        lblIdErr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblIdErrKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAddLocationId, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddLocationName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnAddLocationRefresh)
                        .addGap(86, 86, 86)
                        .addComponent(btnAddNewLocation))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblIdErr, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAddLocationId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(lblIdErr, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAddLocationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddLocationRefresh)
                    .addComponent(btnAddNewLocation))
                .addGap(188, 188, 188))
        );

        jTabbedPane1.addTab("Thêm mới vị trí", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewLocationActionPerformed
        StringBuilder sb = new StringBuilder();
        if(txtAddLocationId.getText().equals("")){
            sb.append("Mã Vị Trí Không Được Để Trống\n");
            if (sb.length()>=0) {
            JOptionPane.showMessageDialog(this, sb.toString(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
        }else if(txtAddLocationName.getText().equals("")){
            sb.append("Tên Vị Trí Không Được Để Trống");
            if (sb.length()>=0) {
            JOptionPane.showMessageDialog(this, sb.toString(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
        }else{
            ViTri vt = new ViTri();
            LocalDate today = LocalDate.now();
            vt.setId(txtAddLocationId.getText());
            vt.setTenViTri(txtAddLocationName.getText());
            vt.setNgayTao(Date.valueOf(today));
            viTriDAOImp.add(vt);
            displayViTri();
            JOptionPane.showMessageDialog(this, "Thêm mới thành công");
        }
    }//GEN-LAST:event_btnAddNewLocationActionPerformed

    private void btnLocationSreachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocationSreachActionPerformed
        if (txtLocationSreach.getText().equals("")) {
            displayViTri();
        }
        try {
            DefaultTableModel table = (DefaultTableModel)tblLocation.getModel();
            String sreach = txtLocationSreach.getText();
            TableRowSorter <DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
            tblLocation.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(sreach));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error" + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLocationSreachActionPerformed

    private void btnLocationDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocationDeleteActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa thông tin không?","Hỏi",JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            int selectedRow = tblLocation.getSelectedRow();
            TableModel model = tblLocation.getModel();
            String id = model.getValueAt(selectedRow, 0).toString();
            viTriDAOImp.remove(id);
            JOptionPane.showMessageDialog(this, "Xóa thành công", "Success", 1);
            displayViTri();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error", "Error", 0);
        }
    }//GEN-LAST:event_btnLocationDeleteActionPerformed

    private void btnLocationUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocationUpdateActionPerformed
        int selectedRow = tblLocation.getSelectedRow();
        TableModel model = tblLocation.getModel();
        String id = model.getValueAt(selectedRow, 0).toString();
        String location = model.getValueAt(selectedRow, 1).toString();
        lu.txtLocationId.setText(id);
        lu.txtLocationName.setText(location);
        lu.setVisible(true);
    }//GEN-LAST:event_btnLocationUpdateActionPerformed

    private void btnAddLocationRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLocationRefreshActionPerformed
        txtAddLocationId.setText("");
        txtAddLocationName.setText("");
    }//GEN-LAST:event_btnAddLocationRefreshActionPerformed

    private void btnLocationRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocationRefreshActionPerformed
        txtLocationSreach.setText("");
        displayViTri();
        JOptionPane.showMessageDialog(rootPane, "Danh sách đã được làm mới", "Thông báo", 1);
    }//GEN-LAST:event_btnLocationRefreshActionPerformed

    private void lblIdErrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblIdErrKeyReleased
        // TODO add your handling code here:
        String pattern = "^VT[0-9]{3}$";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(txtAddLocationId.getText());
        if(!match.matches()){
            lblIdErr.setText("Mã Vị Trí phải có 5 ký tự và theo định dạng VTxxx (x là số)");
        }else{
            lblIdErr.setText("");
        }
    }//GEN-LAST:event_lblIdErrKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViTriIF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViTriIF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViTriIF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViTriIF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViTriIF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLocationRefresh;
    private javax.swing.JButton btnAddNewLocation;
    private javax.swing.JButton btnLocationDelete;
    private javax.swing.JButton btnLocationRefresh;
    private javax.swing.JButton btnLocationSreach;
    private javax.swing.JButton btnLocationUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblIdErr;
    private javax.swing.JTable tblLocation;
    private javax.swing.JTextField txtAddLocationId;
    private javax.swing.JTextField txtAddLocationName;
    private javax.swing.JTextField txtLocationSreach;
    // End of variables declaration//GEN-END:variables

    @Override
    public void doUpdateViTri(String id, String name) {
        try {
            updateViTri(id, name);
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin vị trí thành công", "Thông Báo", 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin vị trí không thành công", "Lỗi", 0);
            e.printStackTrace();
        }
        displayViTri();
    }
}
