/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theloai;

import com.bkap.dao.TheLoaiDAOImp;
import com.bkap.entities.TheLoai;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author TaiyoNg
 */
public class TheLoaiIF extends javax.swing.JInternalFrame{
    TheLoaiDAOImp theLoaiDAOImp;
    CategoryUpdate cu = new CategoryUpdate();
    Date date = new Date();
    /**
     * Creates new form TheLoai
     */
    public TheLoaiIF() {
        theLoaiDAOImp = new TheLoaiDAOImp();
        initComponents();
        jDateChooser1.setDate(date);
        displayCategory();
    }
    
    public void displayCategory(){
        List<TheLoai> data = theLoaiDAOImp.toList();
        DefaultTableModel model = (DefaultTableModel)tblCategory.getModel();
        model.setRowCount(0);
        for (TheLoai tl : data) {
            model.addRow(new Object[] {tl.getId(), tl.getTenTheLoai(), tl.isTrangThai(), tl.getNgayTao()});
        }
        tblCategory.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCategory = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategory = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnCategoryRefresh = new javax.swing.JButton();
        btnCategoryUpdate = new javax.swing.JButton();
        btnCategoryDelete = new javax.swing.JButton();
        pnlAddCategory = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAddCategoryId = new javax.swing.JTextField();
        txtAddCategoryName = new javax.swing.JTextField();
        chbAddCategoryStatus = new javax.swing.JCheckBox();
        btnAddNewCategory = new javax.swing.JButton();
        btnAddCategoryRefresh = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        pnlCategory.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thể loại sách");

        tblCategory.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tblCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên Thể Loại", "Trạng Thái", "Ngày Tạo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCategory);

        txtSearch.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        btnSearch.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnSearch.setText("Tìm Kiếm");

        btnCategoryRefresh.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnCategoryRefresh.setText("Làm Mới");
        btnCategoryRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryRefreshActionPerformed(evt);
            }
        });

        btnCategoryUpdate.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnCategoryUpdate.setText("Cập Nhật");
        btnCategoryUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryUpdateActionPerformed(evt);
            }
        });

        btnCategoryDelete.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnCategoryDelete.setText("Xóa");
        btnCategoryDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCategoryUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnCategoryDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(btnCategoryRefresh)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCategoryRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCategoryUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCategoryDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        pnlCategory.addTab("Thể loại sách", jPanel1);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thêm mới thể loại sách");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Mã thể loại:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Tên thể loại:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Trạng thái:");

        txtAddCategoryId.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        txtAddCategoryName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        chbAddCategoryStatus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        chbAddCategoryStatus.setText("Hiện");

        btnAddNewCategory.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAddNewCategory.setText("Thêm mới");
        btnAddNewCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewCategoryActionPerformed(evt);
            }
        });

        btnAddCategoryRefresh.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAddCategoryRefresh.setText("Làm mới");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Ngày tạo:");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setEnabled(false);
        jDateChooser1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlAddCategoryLayout = new javax.swing.GroupLayout(pnlAddCategory);
        pnlAddCategory.setLayout(pnlAddCategoryLayout);
        pnlAddCategoryLayout.setHorizontalGroup(
            pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddCategoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlAddCategoryLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(52, 52, 52)
                .addGroup(pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddCategoryLayout.createSequentialGroup()
                        .addGroup(pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlAddCategoryLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(btnAddCategoryRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddNewCategory))
                            .addComponent(txtAddCategoryId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddCategoryName, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(207, 207, 207))
                    .addGroup(pnlAddCategoryLayout.createSequentialGroup()
                        .addGroup(pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbAddCategoryStatus)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlAddCategoryLayout.setVerticalGroup(
            pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddCategoryLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addGroup(pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAddCategoryId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAddCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(chbAddCategoryStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCategoryRefresh)
                    .addComponent(btnAddNewCategory))
                .addGap(129, 129, 129))
        );

        pnlCategory.addTab("Thêm mới thể loại", pnlAddCategory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCategory)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCategory, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCategoryUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryUpdateActionPerformed
        // TODO add your handling code here:
        cu.setVisible(true);
    }//GEN-LAST:event_btnCategoryUpdateActionPerformed

    private void tblCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoryMouseClicked
        // TODO add your handling code here:
        int index = tblCategory.getSelectedRow();
        TableModel model = tblCategory.getModel();
        String id = model.getValueAt(index, 0).toString();
        String categoryName = model.getValueAt(index, 1).toString();
        Boolean categoryStatus = (Boolean) model.getValueAt(index, 2);
        
        
        cu.txtCategoryId.setText(id);
        cu.txtCategoryName.setText(categoryName);
        cu.chbCategoryStatus.setSelected(categoryStatus); 
    }//GEN-LAST:event_tblCategoryMouseClicked

    private void btnAddNewCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewCategoryActionPerformed
        // TODO add your handling code here:
        TheLoai tl = new TheLoai();
        String d = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        tl.setId(txtAddCategoryId.getText());
        tl.setTenTheLoai(txtAddCategoryName.getText());
        tl.setTrangThai(chbAddCategoryStatus.isSelected());
        tl.setNgayTao(java.sql.Date.valueOf(d));
        theLoaiDAOImp.add(tl);
        displayCategory();
    }//GEN-LAST:event_btnAddNewCategoryActionPerformed

    private void btnCategoryRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryRefreshActionPerformed
        // TODO add your handling code here:
        displayCategory();
        JOptionPane.showMessageDialog(rootPane, "Bảng danh sách thể loại đã được làm mới", "Thông báo", 1);
    }//GEN-LAST:event_btnCategoryRefreshActionPerformed

    private void btnCategoryDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryDeleteActionPerformed
        // TODO add your handling code here:
        int dialogConfirm = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa không?", "Thông báo", 0);
        if (dialogConfirm == JOptionPane.YES_OPTION) {
            theLoaiDAOImp.remove(cu.txtCategoryId.getText());
            JOptionPane.showMessageDialog(rootPane, "Xóa thể loại thành công", "Thông báo", 1);
            displayCategory();
        }
    }//GEN-LAST:event_btnCategoryDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCategoryRefresh;
    private javax.swing.JButton btnAddNewCategory;
    private javax.swing.JButton btnCategoryDelete;
    private javax.swing.JButton btnCategoryRefresh;
    private javax.swing.JButton btnCategoryUpdate;
    private javax.swing.JButton btnSearch;
    private javax.swing.JCheckBox chbAddCategoryStatus;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlAddCategory;
    private javax.swing.JTabbedPane pnlCategory;
    private javax.swing.JTable tblCategory;
    private javax.swing.JTextField txtAddCategoryId;
    private javax.swing.JTextField txtAddCategoryName;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables


}
