/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theloai;

import com.bkap.dao.TheLoaiDAOImp;
import com.bkap.entities.TheLoai;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author TaiyoNg
 */
public class TheLoaiIF extends javax.swing.JInternalFrame implements CategoryUpdate.CallbackCategory{
    TheLoaiDAOImp theLoaiDAOImp;
    CategoryUpdate cu = new CategoryUpdate(this);
    /**
     * Creates new form TheLoai
     */
    public TheLoaiIF() {
        theLoaiDAOImp = new TheLoaiDAOImp();
        initComponents();
        displayCategory();
    }
    
    public void displayCategory(){
        List<TheLoai> data = theLoaiDAOImp.toList();
        DefaultTableModel model = (DefaultTableModel)tblCategory.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tblCategory.setRowSorter(tr);
        tr.setRowFilter(null);
        String trangThai;
        model.setRowCount(0);
        for (TheLoai tl : data) {
            if (tl.isTrangThai() == true) {
                trangThai = "Hiện";
            }else{
                trangThai = "Ẩn";
            }
            model.addRow(new Object[] {tl.getId(), tl.getTenTheLoai(), trangThai, tl.getNgayTao()});
        }
        tblCategory.setModel(model);
    }
    
    public void updateTheLoai(String id, String name, Boolean status){
        TheLoai tl = new TheLoai();
        tl.setId(id);
        tl.setTenTheLoai(name);
        tl.setTrangThai(status);
        theLoaiDAOImp.edit(tl);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCategory = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategory = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnCategoryRefresh = new javax.swing.JButton();
        btnCategoryUpdate = new javax.swing.JButton();
        btnCategoryDelete = new javax.swing.JButton();
        pnlAddCategory = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAddCategoryId = new javax.swing.JTextField();
        txtAddCategoryName = new javax.swing.JTextField();
        chbAddCategoryStatus = new javax.swing.JCheckBox();
        btnAddNewCategory = new javax.swing.JButton();
        btnAddCategoryRefresh = new javax.swing.JButton();
        lblIdErr = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Quản Lý Thể Loại");

        pnlCategory.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thể loại sách");

        tblCategory.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tblCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên Thể Loại", "Trạng Thái", "Ngày Tạo"
            }
        ));
        tblCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCategory);

        txtSearch.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        btnSearch.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-search-18.png"))); // NOI18N
        btnSearch.setText("Tìm Kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnCategoryRefresh.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnCategoryRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-renew-18.png"))); // NOI18N
        btnCategoryRefresh.setText("Làm Mới");
        btnCategoryRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryRefreshActionPerformed(evt);
            }
        });

        btnCategoryUpdate.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnCategoryUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-update-18.png"))); // NOI18N
        btnCategoryUpdate.setText("Cập Nhật");
        btnCategoryUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryUpdateActionPerformed(evt);
            }
        });

        btnCategoryDelete.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnCategoryDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-delete-bin-18.png"))); // NOI18N
        btnCategoryDelete.setText("Xóa");
        btnCategoryDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCategoryUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnCategoryDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(btnCategoryRefresh)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCategoryRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCategoryUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCategoryDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addGap(128, 128, 128))
        );

        pnlCategory.addTab("Thể loại sách", jPanel1);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thêm mới thể loại sách");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Mã thể loại:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Tên thể loại:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Trạng thái:");

        txtAddCategoryId.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtAddCategoryId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddCategoryIdKeyReleased(evt);
            }
        });

        txtAddCategoryName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        chbAddCategoryStatus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        chbAddCategoryStatus.setText("Hiện");

        btnAddNewCategory.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAddNewCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-property-18.png"))); // NOI18N
        btnAddNewCategory.setText("Thêm mới");
        btnAddNewCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewCategoryActionPerformed(evt);
            }
        });

        btnAddCategoryRefresh.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAddCategoryRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-renew-18.png"))); // NOI18N
        btnAddCategoryRefresh.setText("Làm mới");

        lblIdErr.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblIdErr.setForeground(new java.awt.Color(252, 9, 31));

        javax.swing.GroupLayout pnlAddCategoryLayout = new javax.swing.GroupLayout(pnlAddCategory);
        pnlAddCategory.setLayout(pnlAddCategoryLayout);
        pnlAddCategoryLayout.setHorizontalGroup(
            pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddCategoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlAddCategoryLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(35, 35, 35)
                .addGroup(pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddCategoryLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(chbAddCategoryStatus)
                        .addContainerGap(507, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddCategoryLayout.createSequentialGroup()
                        .addGroup(pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlAddCategoryLayout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(btnAddCategoryRefresh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddNewCategory))
                            .addComponent(txtAddCategoryId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddCategoryName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(207, 207, 207))))
        );
        pnlAddCategoryLayout.setVerticalGroup(
            pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddCategoryLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addGroup(pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAddCategoryId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(lblIdErr, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAddCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(chbAddCategoryStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(pnlAddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCategoryRefresh)
                    .addComponent(btnAddNewCategory))
                .addGap(179, 179, 179))
        );

        pnlCategory.addTab("Thêm mới thể loại", pnlAddCategory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCategory)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCategory, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCategoryUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryUpdateActionPerformed
        // TODO add your handling code here:
        cu.setVisible(true);
    }//GEN-LAST:event_btnCategoryUpdateActionPerformed

    private void tblCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoryMouseClicked
        // TODO add your handling code here:
        int index = tblCategory.getSelectedRow();
        TableModel model = tblCategory.getModel();
        String id = model.getValueAt(index, 0).toString();
        String categoryName = model.getValueAt(index, 1).toString();
        Boolean categoryStatus = null;
        if (model.getValueAt(index, 2).toString().equals("Ẩn")) {
            categoryStatus = false;
        }else{
            categoryStatus = true;
        }
        
        
        cu.txtCategoryId.setText(id);
        cu.txtCategoryName.setText(categoryName);
        cu.chbCategoryStatus.setSelected(categoryStatus); 
    }//GEN-LAST:event_tblCategoryMouseClicked

    private void btnAddNewCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewCategoryActionPerformed
        // TODO add your handling code here:
        try {
            TheLoai tl = new TheLoai();
            LocalDate today = LocalDate.now();
            tl.setId(txtAddCategoryId.getText());
            tl.setTenTheLoai(txtAddCategoryName.getText());
            tl.setTrangThai(chbAddCategoryStatus.isSelected());
            tl.setNgayTao(java.sql.Date.valueOf(today));
            theLoaiDAOImp.add(tl);
            displayCategory();
            JOptionPane.showMessageDialog(rootPane, "Thêm thể loại mới thành công", "Thông báo", 1);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Thêm thể loại mới không thành công", "Lỗi", 0);
            
        }
    }//GEN-LAST:event_btnAddNewCategoryActionPerformed

    private void btnCategoryRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryRefreshActionPerformed
        // TODO add your handling code here:
        displayCategory();
        JOptionPane.showMessageDialog(rootPane, "Bảng danh sách thể loại đã được làm mới", "Thông báo", 1);
    }//GEN-LAST:event_btnCategoryRefreshActionPerformed

    private void btnCategoryDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryDeleteActionPerformed
        // TODO add your handling code here:
        int dialogConfirm = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa không?", "Thông báo", 0);
        if (dialogConfirm == JOptionPane.YES_OPTION) {
            theLoaiDAOImp.remove(cu.txtCategoryId.getText());
            JOptionPane.showMessageDialog(rootPane, "Xóa thể loại thành công", "Thông báo", 1);
            displayCategory();
        }
    }//GEN-LAST:event_btnCategoryDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if (txtSearch.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Xin mời nhập từ khóa tìm kiếm", "Thông báo", 1);
                    
        }else{
            try {
                DefaultTableModel model = (DefaultTableModel)tblCategory.getModel();
                String search = txtSearch.getText();
                TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
                tblCategory.setRowSorter(tr);
                tr.setRowFilter(RowFilter.regexFilter(search));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Error" + e.getMessage());
                e.printStackTrace();
            }
            
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtAddCategoryIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddCategoryIdKeyReleased
        // TODO add your handling code here:
        String pattern = "^TL[0-9]{3}$";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(txtAddCategoryId.getText());
        if(!match.matches()){
            lblIdErr.setText("Mã Thể Loại phải có 5 ký tự và theo định dạng TLxxx (x là số)");
        }else{
            lblIdErr.setText("");
        }
    }//GEN-LAST:event_txtAddCategoryIdKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCategoryRefresh;
    private javax.swing.JButton btnAddNewCategory;
    private javax.swing.JButton btnCategoryDelete;
    private javax.swing.JButton btnCategoryRefresh;
    private javax.swing.JButton btnCategoryUpdate;
    private javax.swing.JButton btnSearch;
    private javax.swing.JCheckBox chbAddCategoryStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIdErr;
    private javax.swing.JPanel pnlAddCategory;
    private javax.swing.JTabbedPane pnlCategory;
    private javax.swing.JTable tblCategory;
    private javax.swing.JTextField txtAddCategoryId;
    private javax.swing.JTextField txtAddCategoryName;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    @Override
    public void DoCategoryUpdate(String id, String name, Boolean status) {
        try {
            updateTheLoai(id, name, status); 
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thể loại thành công", "Thông báo", 1);
            displayCategory();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thể loại không thành công", "Lỗi", 0);
            e.printStackTrace();
        }
    }


}
