/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package docgia;

import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author TaiyoNg
 */
public class UpdateDocGia extends javax.swing.JFrame {
    SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd");
    /**
     * Creates new form UpdateDocGia
     */
    CallbackUpdateDocGia cbud;
    interface CallbackUpdateDocGia{
        public void doUpdateDocGia(String id, String name, String email, boolean male, boolean female, String birthday, String sdt, String address);
    }

    public UpdateDocGia(CallbackUpdateDocGia cbud) {
        initComponents();
        this.cbud = cbud;
    }
    
    public UpdateDocGia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnCancelUpdateReader = new javax.swing.JButton();
        txtUpdateReaderAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rdoUpdateReaderGender1 = new javax.swing.JRadioButton();
        rdoUpdateReaderGender0 = new javax.swing.JRadioButton();
        dchUpdateReaderBirthday = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUpdateReaderPhone = new javax.swing.JTextField();
        txtUpdateReaderEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUpdateReaderName = new javax.swing.JTextField();
        txtUpdateReaderId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnUpdateReader = new javax.swing.JButton();
        lblIdErr = new javax.swing.JLabel();
        lblEmailErr = new javax.swing.JLabel();
        lblPhoneErr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cập Nhật Thông Tin Độc Giả");

        btnCancelUpdateReader.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCancelUpdateReader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-cancel-18.png"))); // NOI18N
        btnCancelUpdateReader.setText("Hủy");
        btnCancelUpdateReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelUpdateReaderActionPerformed(evt);
            }
        });

        txtUpdateReaderAddress.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Địa Chỉ:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Giới Tính:");

        buttonGroup1.add(rdoUpdateReaderGender1);
        rdoUpdateReaderGender1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rdoUpdateReaderGender1.setText("Nam");

        buttonGroup1.add(rdoUpdateReaderGender0);
        rdoUpdateReaderGender0.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rdoUpdateReaderGender0.setText("Nữ");

        dchUpdateReaderBirthday.setDateFormatString("yyyy-MM-dd");
        dchUpdateReaderBirthday.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Ngày Sinh:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Số Điện Thoại:");

        txtUpdateReaderPhone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtUpdateReaderPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUpdateReaderPhoneKeyReleased(evt);
            }
        });

        txtUpdateReaderEmail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtUpdateReaderEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUpdateReaderEmailKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Email:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Tên Độc Giả:");

        txtUpdateReaderName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        txtUpdateReaderId.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtUpdateReaderId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUpdateReaderIdKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Mã Độc Giả:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cập nhật thông tin Độc Giả");

        btnUpdateReader.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnUpdateReader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-update-18.png"))); // NOI18N
        btnUpdateReader.setText("Cập Nhật");
        btnUpdateReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateReaderActionPerformed(evt);
            }
        });

        lblIdErr.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblIdErr.setForeground(new java.awt.Color(248, 4, 19));

        lblEmailErr.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblEmailErr.setForeground(new java.awt.Color(248, 4, 19));

        lblPhoneErr.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblPhoneErr.setForeground(new java.awt.Color(248, 4, 19));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhoneErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmailErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIdErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUpdateReaderId)
                    .addComponent(txtUpdateReaderName)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoUpdateReaderGender1)
                                .addGap(48, 48, 48)
                                .addComponent(rdoUpdateReaderGender0))
                            .addComponent(dchUpdateReaderBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUpdateReaderAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtUpdateReaderEmail)
                    .addComponent(txtUpdateReaderPhone))
                .addGap(141, 141, 141))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelUpdateReader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdateReader)
                .addGap(63, 63, 63))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUpdateReaderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(lblIdErr, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUpdateReaderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUpdateReaderEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(lblEmailErr, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUpdateReaderPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(lblPhoneErr, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(dchUpdateReaderBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rdoUpdateReaderGender1)
                    .addComponent(rdoUpdateReaderGender0))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtUpdateReaderAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelUpdateReader)
                    .addComponent(btnUpdateReader))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateReaderActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn cập nhật thông tin độc giả ?", "Xác Nhận", 0);
        if(choice == JOptionPane.NO_OPTION){
            return;
        }
        cbud.doUpdateDocGia(txtUpdateReaderId.getText(), txtUpdateReaderName.getText(), 
                txtUpdateReaderEmail.getText(), rdoUpdateReaderGender1.isSelected() , rdoUpdateReaderGender0.isSelected(), 
                String.valueOf(sf.format(dchUpdateReaderBirthday.getDate())), txtUpdateReaderPhone.getText(), txtUpdateReaderAddress.getText());
        dispose();
    }//GEN-LAST:event_btnUpdateReaderActionPerformed

    private void btnCancelUpdateReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelUpdateReaderActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelUpdateReaderActionPerformed

    private void txtUpdateReaderIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUpdateReaderIdKeyReleased
        // TODO add your handling code here:
        String pattern = "^DG[0-9]{3}$";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(txtUpdateReaderId.getText());
        if(!match.matches()){
            lblIdErr.setText("Mã người đọc phải có 5 ký tự và theo định dạng BKxxx (x là số)");
        }else{
            lblIdErr.setText("");
        }
    }//GEN-LAST:event_txtUpdateReaderIdKeyReleased

    private void txtUpdateReaderEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUpdateReaderEmailKeyReleased
        // TODO add your handling code here:
        String pattern = "^[a-z][a-z0-9_\\.]{5,32}@[a-z0-9-]{2,}(\\.[a-z0-9]{2,4}){1,2}$";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(txtUpdateReaderEmail.getText());
        if(!match.matches()){
            lblEmailErr.setText("Định dạng email không đúng");
        }else{
            lblEmailErr.setText("");
        }
    }//GEN-LAST:event_txtUpdateReaderEmailKeyReleased

    private void txtUpdateReaderPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUpdateReaderPhoneKeyReleased
        // TODO add your handling code here:
        String pattern = "^0((3[2-9])|(5[689])|(7[06-9])|(8[1-689])|(9[0-46-9]))(\\d{7})$";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(txtUpdateReaderPhone.getText());
        if(!match.matches()){
            lblPhoneErr.setText("Số điện thoại phải đúng định dạng và theo nhà mạng Việt Nam");
        }else{
            lblPhoneErr.setText("");
        }
    }//GEN-LAST:event_txtUpdateReaderPhoneKeyReleased
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDocGia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelUpdateReader;
    private javax.swing.JButton btnUpdateReader;
    private javax.swing.ButtonGroup buttonGroup1;
    public com.toedter.calendar.JDateChooser dchUpdateReaderBirthday;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblEmailErr;
    private javax.swing.JLabel lblIdErr;
    private javax.swing.JLabel lblPhoneErr;
    public javax.swing.JRadioButton rdoUpdateReaderGender0;
    public javax.swing.JRadioButton rdoUpdateReaderGender1;
    public javax.swing.JTextField txtUpdateReaderAddress;
    public javax.swing.JTextField txtUpdateReaderEmail;
    public javax.swing.JTextField txtUpdateReaderId;
    public javax.swing.JTextField txtUpdateReaderName;
    public javax.swing.JTextField txtUpdateReaderPhone;
    // End of variables declaration//GEN-END:variables
}
